traefik_image: "traefik:3.7"
traefik_install_dir: /opt/traefik
traefik_log_dir: /var/log/traefik
traefik_log_level: INFO

traefik_network_external: traefik
postgres_network_external: postgres

traefik_container_name: traefik

traefik_tunnel_entrypoint_port: 80

traefik_websecure_entrypoint_port: 443
traefik_acme_root_domain: ""
traefik_acme_email: ""
traefik_acme_use_staging: false

traefik_acme_cf_dns_api_token: ""
