- name: Converge
  hosts: all
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  vars:
    traefik_acme_cf_dns_api_token: "molecule-placeholder-token"
    traefik_acme_domains:
      - "example.com"
      - "example.org"
    traefik_acme_email: "ops@example.com"
    traefik_acme_wait: false
  pre_tasks:
    - name: Install apt-utils to avoid dpkg warnings
      ansible.builtin.apt:
        name: apt-utils
        state: present
        update_cache: true
  roles:
    - role: docker
    - role: traefik
