- name: Query Docker Swarm state
  ansible.builtin.command: docker info --format '{% raw %}{{ .Swarm.LocalNodeState }}{% endraw %}'
  register: swarm_local_node_state
  changed_when: false

- name: Initialize the single-node Docker Swarm
  ansible.builtin.command: docker swarm init --advertise-addr {{ swarm_advertise_addr }}
  register: swarm_init
  changed_when: swarm_init.rc == 0
  when: swarm_local_node_state.stdout != "active"
