dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/../
  inventory:
    host_vars:
      instance:
        pg_shared_user: "molecule_admin"
        pg_shared_password: "molecule_admin_pw"
        preview_tenant_name: "molecule_tenant"
        preview_tenant_password: "molecule_tenant_pw"
        preview_tenant_connection_limit: 25
        preview_tenant_authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFlGtJm+A7zY61/nn6hHk9L8u95LRTVAeNBV3/XLFYXV molecule@tenant-test"
verifier:
  name: ansible
