- name: Converge
  hosts: all
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  pre_tasks:
    - name: Install apt-utils to avoid dpkg warnings
      ansible.builtin.apt:
        name: apt-utils
        state: present
        update_cache: true
  roles:
    - role: docker
    - role: postgres_shared
  post_tasks:
    - name: Provision a test tenant
      ansible.builtin.include_role:
        name: prod_tenant
      vars:
        prod_tenant_name: molecule_tenant
        prod_tenant_password: molecule_tenant_pw
